name: Check pull request
on:
    - pull_request
jobs:
    build:
        name: Build
        uses: recrafter-group/.github/.github/workflows/build.yml@version/2.0.0
    analyze:
        name: Analyze
        uses: recrafter-group/.github/.github/workflows/analyze.yml@version/2.0.0
        needs:
            - build
    test:
        name: Test
        uses: recrafter-group/.github/.github/workflows/test.yml@version/2.0.0
    mutation_test:
        name: Mutation test
        uses: recrafter-group/.github/.github/workflows/mutation_test.yml@version/2.1.0
        permissions:
            contents: read
            pull-requests: write
